# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 866b61926e9ca7f38c0f80dda2d593e43c74ec4316427168712dbf813c20887ca1e5f68f2af84f8bd1d0371f113e6a44db79ce5d3a9f178d012757525bb46f29

test:
  secret_key_base: 2dd1507efccca464bf59ce4d7c79ac97087c57ffa99c299ab7ffaf9161e7ada9496611f5f709d0b07e7fa012b0777cd9542091fa04308c35d0cee8673f5d7679

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
